// Code generated by "stringer -type=DagRun -linecomment"; DO NOT EDIT.

package fns

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[DagRunRegular-0]
	_ = x[DagRunProvider-1]
	_ = x[DagRunInventory-2]
}

const _DagRun_name = "RegularProviderInventory"

var _DagRun_index = [...]uint8{0, 7, 15, 24}

func (i DagRun) String() string {
	if i < 0 || i >= DagRun(len(_DagRun_index)-1) {
		return "DagRun(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _DagRun_name[_DagRun_index[i]:_DagRun_index[i+1]]
}
